### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lucywyman** [joekhoobyar/net-ssh-kerberos#7]
Hello! I'm sure this has come up before, but we're creating an Apache licensed project http://github.com/puppetlabs/bolt and would not like for it to be held to the GPL license. Is the license flexible at all? I believe that LGPL, GPLv3, or Apache would allow us to maintain Bolt's Apache license (or others, we're open to discussion) @joekhoobyar @jballanc

**Comment by jballanc** [comment]
My only contribution to this project is extremely minor. If you need approval, I would gladly re-license that single line change under a more permissive license. I wonder, though, this gem has not been touched in some years. Perhaps a clean-room re-implementation might be called for?
